apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fya1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qgvx-tenant/rhtap-demo-app/hacbs-test-project-fya1@sha256:fc00059c7c56d1064dfdf63c52408d925aa5b686b94957d7a58b1ce2f0506dc5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
